service: peters-serverless-function
provider:
  name: aws
  runtime: nodejs6.10


functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: feed
          method: get
